export { default as ClockIcon } from './clock'
export { default as CupIcon } from './cup'
export { default as UserIcon } from './user'
export { default as LikeIcon } from './like'
export { default as LogoIcon } from './logo'