export { default as ClockIcon } from './clock'
export { default as CupIcon } from './cup'
export { default as UserIcon } from './user'
export { default as LikeIcon } from './like'
export { default as LogoIcon } from './logo'
export { default as PlusIcon } from './plus'
export { default as ArrowRightIcon } from './arrowRight'
export { default as MinusIcon } from './minus'